const defaultSteps = [
  { title:'確認考試公告頁面', copy:'先打開主辦單位提供的模擬測驗公告，確認目前查詢入口。', note:'請使用最新公告連結', tag:'操作說明' },
  { title:'找到准考證查詢入口', copy:'在頁面上找到「准考證查詢」按鈕，點擊進入查詢畫面。', note:'入口通常在頁面上方', tag:'操作說明' },
  { title:'輸入基本資料', copy:'依照畫面提示輸入姓名、身分證字號或其他必要資料。', note:'請確認資料沒有多餘空格', tag:'提醒' },
  { title:'完成驗證', copy:'輸入驗證碼，並再次檢查每一欄資料是否正確。', note:'看不清楚時可重新取得驗證碼', tag:'提醒' },
  { title:'點擊「查詢」', copy:'確認資料後，點擊畫面上的「查詢」按鈕送出。', note:'按鈕會被系統自動標示', tag:'小技巧' },
  { title:'查看並保存准考證號碼', copy:'查詢結果出現後，記下自己的准考證號碼，或截圖保存。', note:'建議同時記錄考試日期與場次', tag:'小技巧' }
];
const DRAFT_KEY='sop-studio-draft-v1'; let steps = structuredClone(defaultSteps); let selectedIndex = 0; let template = 'guide'; let draggedIndex = null; let videoFrames = []; let transcriptSegments = []; let visualMode = 'plain'; let frameStyle = 'paper';
const $ = (s) => document.querySelector(s); const $$ = (s) => [...document.querySelectorAll(s)];
function showToast(message){ const el=$('#toast'); el.textContent=message; el.classList.add('show'); clearTimeout(window.toastTimer); window.toastTimer=setTimeout(()=>el.classList.remove('show'),2600); }
function saveDraft(){ try { localStorage.setItem(DRAFT_KEY,JSON.stringify({topic:$('#topic').value,steps,template,frameStyle,visualMode,savedAt:new Date().toISOString()})); $('#saveState').innerHTML='<span class="status-dot"></span> 已儲存於本機'; } catch(error){ $('#saveState').innerHTML='<span class="status-dot"></span> 暫存失敗'; } }
function loadDraft(){ try { const draft=JSON.parse(localStorage.getItem(DRAFT_KEY)||'null'); if(!draft?.steps?.length)return false; steps=draft.steps; template=draft.template||'guide'; frameStyle=draft.frameStyle||'paper'; visualMode=draft.visualMode||'plain'; if(draft.topic)$('#topic').value=draft.topic; $$('.template-button').forEach(button=>button.classList.toggle('active',button.dataset.template===template)); $$('.frame-tool').forEach(button=>button.classList.toggle('active',button.dataset.frame===frameStyle)); $('#saveState').innerHTML='<span class="status-dot"></span> 已恢復本機草稿'; return true; } catch(error){ return false; } }
function downloadFile(filename,content,type){ const blob=new Blob([content],{type}); const link=document.createElement('a'); link.href=URL.createObjectURL(blob); link.download=filename; link.click(); setTimeout(()=>URL.revokeObjectURL(link.href),1000); }
function projectData(){ return {format:'sop-studio-project',version:1,topic:$('#topic').value,template,frameStyle,visualMode,steps,transcriptSegments,frames:videoFrames,savedAt:new Date().toISOString()}; }
function exportProjectJson(){ downloadFile('sop-studio-project.json',JSON.stringify(projectData(),null,2),'application/json'); showToast('JSON 專案檔已下載'); }
function exportProjectMarkdown(){ const lines=[`# ${$('#topic').value||'未命名 SOP'}`,'',`> 模板：${template}`,'',`共 ${steps.length} 個步驟`,'']; steps.forEach((step,index)=>{const frame=videoFrames.find(f=>f.id===step.frameId); lines.push(`## ${String(index+1).padStart(2,'0')}. ${step.title}`,'',step.copy,'',`- 類型：${step.tag}`,`- 提醒：${step.note}`,`- 操作畫面：${frame?'已配畫面':'尚未指定'}`,'');}); downloadFile('sop-studio-project.md',lines.join('\n'),'text/markdown;charset=utf-8'); showToast('Markdown 文件已下載'); }
async function exportProjectZip(){ try { const response=await fetch('/api/export-zip',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(projectData())}); if(!response.ok)throw new Error(); const blob=await response.blob(); downloadFile('sop-studio-project.zip',blob,'application/zip'); showToast('ZIP 專案檔已下載'); } catch(error){ showToast('ZIP 需要從開啟SOPStudio.cmd啟動的網站下載'); } }
function importProjectJson(file){ const reader=new FileReader(); reader.onload=()=>{try{const project=JSON.parse(reader.result); if(!Array.isArray(project.steps)||!project.steps.length)throw new Error('找不到步驟資料'); steps=project.steps; template=project.template||'guide'; frameStyle=project.frameStyle||'paper'; visualMode=project.visualMode||'plain'; transcriptSegments=project.transcriptSegments||[]; videoFrames=project.frames||[]; if(project.topic)$('#topic').value=project.topic; $$('.template-button').forEach(button=>button.classList.toggle('active',button.dataset.template===template)); $$('.frame-tool').forEach(button=>button.classList.toggle('active',button.dataset.frame===frameStyle)); renderSteps(); saveDraft(); showToast(`已載入 ${steps.length} 個步驟`);}catch(error){showToast('JSON 格式不正確，無法載入');}}; reader.readAsText(file); }
let saveTimer; function queueSave(){ clearTimeout(saveTimer); $('#saveState').innerHTML='<span class="status-dot"></span> 編輯中...'; saveTimer=setTimeout(saveDraft,500); }
function renderSteps(){ $('#stepList').innerHTML=steps.map((step,i)=>{ const frame=videoFrames.find(f=>f.id===step.frameId); return `<article class="step-card ${i===selectedIndex?'selected':''}" draggable="true" data-index="${i}"><span class="drag-handle">⋮⋮</span><span class="step-number">${String(i+1).padStart(2,'0')}</span><div class="step-content"><input class="step-title" value="${step.title}" aria-label="步驟${i+1}標題" /><textarea class="step-copy" rows="1" aria-label="步驟${i+1}說明">${step.copy}</textarea><div class="step-tags"><span class="tag">${step.tag}</span><span class="tag tip">${step.note}</span>${frame?'<span class="tag source-tag">已配畫面</span>':'<span class="tag unlinked-tag">尚未配畫面</span>'}</div></div><button class="step-delete" aria-label="刪除步驟 ${i+1}" title="刪除步驟">×</button></article>`;}).join(''); $('#stepSummary').textContent=`共 ${steps.length} 個步驟`; bindStepEvents(); renderPreview(); }
function bindStepEvents(){ $$('.step-card').forEach(card=>{ const i=Number(card.dataset.index); card.addEventListener('click',()=>{selectedIndex=i; renderSteps();}); card.addEventListener('dragstart',()=>{draggedIndex=i; card.classList.add('dragging');}); card.addEventListener('dragend',()=>card.classList.remove('dragging')); card.addEventListener('dragover',e=>e.preventDefault()); card.addEventListener('drop',e=>{e.preventDefault(); if(draggedIndex===null||draggedIndex===i)return; const [moved]=steps.splice(draggedIndex,1); steps.splice(i,0,moved); selectedIndex=i; draggedIndex=null; renderSteps(); queueSave(); showToast('步驟順序已更新');}); const title=card.querySelector('.step-title'); const copy=card.querySelector('.step-copy'); [title,copy].forEach(field=>field.addEventListener('click',e=>e.stopPropagation())); title.addEventListener('input',e=>{steps[i].title=e.target.value; renderPreview(); queueSave();}); copy.addEventListener('input',e=>{steps[i].copy=e.target.value; renderPreview(); queueSave();}); card.querySelector('.step-delete').addEventListener('click',e=>{e.stopPropagation(); if(steps.length===1)return showToast('至少保留一個步驟'); steps.splice(i,1); selectedIndex=Math.min(selectedIndex,steps.length-1); renderSteps(); queueSave(); showToast('步驟已刪除');}); }); }
function annotationHtml(){ const step=steps[selectedIndex]||{}; const mode=step.visualMode||visualMode; const x=step.annotationX??62, y=step.annotationY??36; const position=` style="left:${x}%;top:${y}%;"`; return mode==='arrow'?`<span class="annotation-arrow annotation-move"${position}>↙</span>`:mode==='box'?`<span class="annotation-box annotation-move"${position}></span>`:mode==='number'?`<span class="annotation-number annotation-move"${position}>${String(selectedIndex+1).padStart(2,'0')}</span>`:mode==='focus'?`<span class="annotation-focus annotation-move"${position}></span>`:''; }
function frameClass(){ return frameStyle==='browser'?'frame-browser':frameStyle==='plain'?'frame-plain':'frame-paper'; }
function bindAnnotationDrag(){ const target=$('#previewStage .annotation-move'); const image=$('#previewStage .real-frame, #previewStage .comic-frame'); if(!target||!image)return; target.addEventListener('pointerdown',event=>{event.preventDefault(); target.setPointerCapture?.(event.pointerId); const startX=event.clientX,startY=event.clientY,originX=parseFloat(target.style.left),originY=parseFloat(target.style.top),rect=image.getBoundingClientRect(); const move=moveEvent=>{const x=Math.max(2,Math.min(92,originX+(moveEvent.clientX-startX)/rect.width*100)),y=Math.max(2,Math.min(86,originY+(moveEvent.clientY-startY)/rect.height*100)); target.style.left=`${x}%`; target.style.top=`${y}%`; steps[selectedIndex].annotationX=x; steps[selectedIndex].annotationY=y;}; const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);queueSave();}; window.addEventListener('pointermove',move);window.addEventListener('pointerup',up);}); }
function renderPreview(){ const step=steps[selectedIndex]||steps[0]; const frame=videoFrames.find(f=>f.id===step.frameId); const page=`${selectedIndex+1} / ${steps.length}`; $('#previewPage').textContent=page; $('#previewTitle').textContent=template==='guide'?'教學講義':template==='comic'?'漫畫對話':'社群圖卡'; const image=frame?`<div class="sheet-image real-frame ${frameClass()}"><img src="${frame.dataUrl}" alt="操作畫面">${annotationHtml()}</div>`:'<div class="sheet-image"><span class="image-placeholder">請從左側影片畫面選擇對應素材</span></div>'; let content=''; if(template==='comic'){ content=`<div class="comic-character"><span class="comic-face">小編</span> SOP 小幫手</div><h3>${step.title}</h3><div class="comic-bubble">${step.copy}</div>${frame?`<div class="comic-frame"><img src="${frame.dataUrl}" alt="操作畫面">${annotationHtml()}</div>`:''}<div class="comic-bubble">小提醒：${step.note}</div>`; } else { content=`<h3>${step.title}</h3><p>${step.copy}</p>${image}<div class="sheet-callout"><strong>${step.tag}</strong><span>${step.note}</span></div>`; } $('#previewStage').innerHTML=`<div class="guide-sheet ${template}"><div class="sheet-top"><span class="sheet-step">STEP ${String(selectedIndex+1).padStart(2,'0')}</span><span class="sheet-count">查詢准考證號碼</span></div>${content}</div>`; bindAnnotationDrag(); }
$$('.input-tab').forEach(tab=>tab.addEventListener('click',()=>{ $$('.input-tab').forEach(x=>x.classList.remove('active')); $$('.input-pane').forEach(x=>x.classList.remove('active')); tab.classList.add('active'); $(`#${tab.dataset.tab}-pane`).classList.add('active'); }));
$$('.template-button').forEach(btn=>btn.addEventListener('click',()=>{template=btn.dataset.template; $$('.template-button').forEach(x=>x.classList.remove('active')); btn.classList.add('active'); renderPreview(); queueSave();}));
$$('.visual-tool').forEach(btn=>btn.addEventListener('click',()=>{visualMode=btn.dataset.visual; if(steps[selectedIndex])steps[selectedIndex].visualMode=visualMode; $$('.visual-tool').forEach(x=>x.classList.toggle('active',x===btn)); renderPreview(); queueSave();}));
$$('.frame-tool').forEach(btn=>btn.addEventListener('click',()=>{frameStyle=btn.dataset.frame; $$('.frame-tool').forEach(x=>x.classList.toggle('active',x===btn)); renderPreview(); queueSave();}));
function exportAllSteps(format='PDF'){ const popup=window.open('','_blank','width=900,height=900'); if(!popup)return showToast('瀏覽器封鎖了彈出視窗，請允許本網站開啟視窗'); const pages=steps.map((step,index)=>{ const frame=videoFrames.find(f=>f.id===step.frameId); const image=frame?`<div class="sheet-image real-frame"><img src="${frame.dataUrl}" alt="操作畫面"><span>畫面 ${frame.timeLabel}</span></div>`:'<div class="sheet-image"><span class="image-placeholder">尚未指定操作畫面</span></div>'; const body=template==='comic'?`<div class="comic-character">SOP 小幫手</div><h2>${step.title}</h2><div class="comic-bubble">${step.copy}</div>${frame?`<div class="comic-frame"><img src="${frame.dataUrl}" alt="操作畫面"></div>`:''}<div class="comic-bubble">小提醒：${step.note}</div>`:`<h2>${step.title}</h2><p>${step.copy}</p>${image}<div class="callout"><strong>${step.tag}</strong><span>${step.note}</span></div>`; return `<section class="page ${template}"><div class="top"><b>STEP ${String(index+1).padStart(2,'0')}</b><span>${index+1} / ${steps.length}</span></div>${body}</section>`; }).join(''); popup.document.write(`<html><head><title>SOP Studio 匯出</title><style>*{box-sizing:border-box}body{margin:0;background:#e9ece8;font-family:Arial,'Noto Sans TC',sans-serif;color:#26313a}.page{width:760px;min-height:960px;margin:24px auto;padding:54px;background:#fff;page-break-after:always}.page.comic{background:#fff8ed}.page.social{background:#27333c;color:#fff}.top{display:flex;justify-content:space-between;color:#e8664e;font-size:13px}.top span{color:#879396}h2{margin:70px 0 18px;font-size:32px}p{color:#6c7b82;line-height:1.8}.sheet-image{height:330px;margin:34px 0;background:#e9f3ef;position:relative;overflow:hidden;border-radius:8px}.sheet-image img,.comic-frame img{width:100%;height:100%;object-fit:contain}.sheet-image span{position:absolute;right:12px;bottom:12px;padding:6px 9px;color:#fff;background:#26313acc;border-radius:5px;font-size:12px}.image-placeholder{display:grid;place-items:center;height:100%;color:#91a09e}.callout,.comic-bubble{padding:16px;margin-top:20px;background:#eef7f0;border-left:4px solid #75ad91}.callout strong,.callout span{display:block}.callout span{margin-top:6px;color:#668077}.comic-character{color:#c64d39;font-weight:bold}.comic-bubble{border:2px solid #26313a;border-left:2px solid #26313a;border-radius:14px;background:#fff}.comic-frame{height:330px;margin:20px 0;overflow:hidden;border:2px solid #26313a}@media print{body{background:#fff}.page{margin:0;width:auto;min-height:0;height:100vh;padding:40px;page-break-after:always}} </style></head><body>${pages}</body></html>`); popup.document.close(); popup.focus(); setTimeout(()=>popup.print(),400); showToast(`已準備 ${steps.length} 頁完整${format}輸出`); }
$('#addStep').addEventListener('click',()=>{steps.push({title:'新的操作步驟',copy:'請補上這一步的操作說明。',note:'補充提醒',tag:'操作說明'}); selectedIndex=steps.length-1; renderSteps(); queueSave(); showToast('已新增步驟');});
$('#saveDraftButton').addEventListener('click',()=>{saveDraft(); showToast('草稿已儲存於目前網站');});
$('#exportJsonButton').addEventListener('click',exportProjectJson); $('#exportMarkdownButton').addEventListener('click',exportProjectMarkdown); $('#exportZipButton').addEventListener('click',exportProjectZip); $('#importJsonButton').addEventListener('click',()=>$('#importJsonInput').click()); $('#importJsonInput').addEventListener('change',event=>{if(event.target.files[0])importProjectJson(event.target.files[0]);});
$('#generateBtn').addEventListener('click',()=>{const btn=$('#generateBtn'); btn.disabled=true; btn.textContent='整理素材中...'; setTimeout(()=>{btn.disabled=false; btn.innerHTML='<span>✦</span> 產生 5～10 個步驟'; renderSteps(); showToast('已根據素材整理出 6 個步驟');},850);});
$('#resetDemo').addEventListener('click',()=>{steps=structuredClone(defaultSteps); selectedIndex=0; template='guide'; videoFrames=[]; transcriptSegments=[]; localStorage.removeItem(DRAFT_KEY); $('#videoKeyframes').innerHTML=''; $('#transcriptList').innerHTML=''; $('#applyTranscript').disabled=true; $('#videoStatus').hidden=true; $('#videoCapture').hidden=true; $('#videoPreview').removeAttribute('src'); $$('.template-button').forEach((x,i)=>x.classList.toggle('active',i===0)); renderSteps(); saveDraft(); showToast('示範內容已重設');});
async function exportSocialCards(){ const canvas=document.createElement('canvas'); canvas.width=1080; canvas.height=1350; const ctx=canvas.getContext('2d'); for(const [index,step] of steps.entries()){ ctx.fillStyle='#27333c'; ctx.fillRect(0,0,canvas.width,canvas.height); ctx.fillStyle='#e8664e'; ctx.font='700 28px Arial'; ctx.fillText(`STEP ${String(index+1).padStart(2,'0')}`,72,92); ctx.fillStyle='#fff'; ctx.font='700 48px Arial'; ctx.fillText(step.title.slice(0,18),72,190); ctx.fillStyle='#c7d0d0'; ctx.font='28px Arial'; const words=step.copy.slice(0,80); ctx.fillText(words.slice(0,28),72,250); ctx.fillText(words.slice(28,56),72,292); ctx.fillText(words.slice(56,84),72,334); const frame=videoFrames.find(f=>f.id===step.frameId); if(frame){ await new Promise(resolve=>{const img=new Image(); img.onload=()=>{ctx.fillStyle='#fff';ctx.fillRect(72,410,936,610);const scale=Math.min(936/img.width,610/img.height);ctx.drawImage(img,72+(936-img.width*scale)/2,410+(610-img.height*scale)/2,img.width*scale,img.height*scale);resolve();};img.src=frame.dataUrl;}); } ctx.fillStyle='#eef7f0';ctx.fillRect(72,1080,936,150);ctx.fillStyle='#416b59';ctx.font='700 25px Arial';ctx.fillText(step.tag,98,1135);ctx.font='22px Arial';ctx.fillText(step.note.slice(0,42),98,1180); await new Promise(resolve=>canvas.toBlob(blob=>{const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`sop-step-${String(index+1).padStart(2,'0')}.png`;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);resolve();},'image/png')); } showToast(`已批次下載 ${steps.length} 張社群圖卡`); }
$('#exportTop').addEventListener('click',()=>exportAllSteps('PDF')); $$('.export-card').forEach(btn=>btn.addEventListener('click',()=>{if(btn.dataset.export==='PDF') exportAllSteps('PDF'); else if(btn.dataset.export==='圖卡') exportSocialCards(); else showToast(`已準備 ${steps.length} 段影片腳本，旁白與字幕會依步驟稿生成`);}));
$('#imageInput').addEventListener('change',e=>{ if(e.target.files.length){showToast(`已加入 ${e.target.files.length} 張截圖素材`);}});
function addFrameCard(frame){ const container=$('#videoKeyframes'); const card=document.createElement('button'); card.type='button'; card.className='keyframe-card'; card.dataset.frameId=frame.id; card.innerHTML=`<img src="${frame.dataUrl}" alt="操作畫面"><span>指派給步驟</span>`; card.addEventListener('click',()=>{steps[selectedIndex].frameId=frame.id; $$('.keyframe-card').forEach(x=>x.classList.toggle('assigned',x.dataset.frameId===frame.id)); renderSteps(); showToast(`已將畫面配給步驟 ${selectedIndex+1}`);}); container.appendChild(card); }
function captureCurrentFrame(){ const video=$('#videoPreview'); if(!video.duration) return showToast('請先載入影片'); const canvas=document.createElement('canvas'); canvas.width=960; canvas.height=Math.max(1,Math.round(960*(video.videoHeight/video.videoWidth))); canvas.getContext('2d').drawImage(video,0,0,canvas.width,canvas.height); const time=video.currentTime; const frame={id:`frame-manual-${Date.now()}`,dataUrl:canvas.toDataURL('image/jpeg',.88),timeLabel:`${time.toFixed(1)} 秒`}; videoFrames.push(frame); addFrameCard(frame); showToast(`已手動擷取 ${frame.timeLabel} 畫面`); }
async function extractVideoKeyframes(file){
  const status=$('#videoStatus'), container=$('#videoKeyframes');
  status.hidden=false; status.innerHTML='<strong>正在讀取影片...</strong><br>瀏覽器會在本機擷取代表畫面，不會上傳影片。'; container.innerHTML='';
  const url=URL.createObjectURL(file); const video=document.createElement('video'); video.preload='metadata'; video.muted=true; video.playsInline=true; video.src=url;
  try {
    await new Promise((resolve,reject)=>{ video.onloadedmetadata=resolve; video.onerror=()=>reject(new Error('影片格式無法讀取')); });
    const duration=video.duration; const times=duration>2?[0,Math.max(0.1,duration*.5),Math.max(0.2,duration-.1)]:[0]; const canvas=document.createElement('canvas');
    canvas.width=960; canvas.height=Math.max(1,Math.round(960*(video.videoHeight/video.videoWidth)));
    videoFrames=[];
    for(const [index,time] of times.entries()){ video.currentTime=time; await new Promise((resolve,reject)=>{video.onseeked=resolve; video.onerror=()=>reject(new Error('無法定位影片畫面'));}); const ctx=canvas.getContext('2d'); ctx.drawImage(video,0,0,canvas.width,canvas.height); const frame={id:`frame-${index}`,dataUrl:canvas.toDataURL('image/jpeg',.84),timeLabel:`${time.toFixed(1)} 秒`}; videoFrames.push(frame); addFrameCard(frame); }
    const preview=$('#videoPreview'); preview.src=URL.createObjectURL(file); preview.onloadedmetadata=()=>{ $('#videoCapture').hidden=false; $('#frameScrubber').max=preview.duration; $('#durationLabel').textContent=`${preview.duration.toFixed(1)} 秒`; $('#transcribeButton').disabled=false; };
    status.innerHTML=`<strong>${file.name}</strong><br>已擷取 ${times.length} 張代表畫面。找不到需要的畫面時，可拖曳時間軸後按「擷取目前這一格」。`; showToast(`影片已擷取 ${times.length} 張代表畫面`);
  } catch(error){ status.innerHTML=`<strong>影片讀取失敗</strong><br>${error.message}。請改用 MP4（H.264）或 MOV。`; showToast('影片格式目前無法讀取'); } finally { URL.revokeObjectURL(url); }
}
$('#videoInput').addEventListener('change',e=>{if(e.target.files.length)extractVideoKeyframes(e.target.files[0]);}); $('#frameScrubber').addEventListener('input',e=>{const video=$('#videoPreview'); video.currentTime=Number(e.target.value); $('#currentTimeLabel').textContent=`${video.currentTime.toFixed(1)} 秒`;}); $('#videoPreview').addEventListener('timeupdate',e=>{$('#frameScrubber').value=e.target.currentTime; $('#currentTimeLabel').textContent=`${e.target.currentTime.toFixed(1)} 秒`;}); $('#captureFrame').addEventListener('click',captureCurrentFrame); $('#addUrl').addEventListener('click',()=>{if($('#urlInput').value)showToast('公開網址已加入素材來源');else showToast('請先輸入公開網址');});
$('#transcribeButton').addEventListener('click',async()=>{ const file=$('#videoInput').files[0]; if(!file)return; const status=$('#transcriptStatus'), list=$('#transcriptList'), button=$('#transcribeButton'); status.textContent='轉錄中...'; button.disabled=true; list.innerHTML=''; try { const form=new FormData(); form.append('video',file); const response=await fetch('/api/transcribe',{method:'POST',body:form}); const data=await response.json(); if(!response.ok)throw new Error(data.error||'轉錄失敗'); transcriptSegments=data.segments; data.segments.forEach(segment=>{const row=document.createElement('div'); row.className='transcript-line'; row.innerHTML=`<span class="transcript-time">${segment.start.toFixed(1)}s</span><span>${segment.text}</span>`; row.addEventListener('click',()=>{$('#videoPreview').currentTime=segment.start;}); list.appendChild(row);}); status.textContent=`完成 ${data.segments.length} 段`; $('#applyTranscript').disabled=!data.segments.length; showToast('語音逐字稿已完成'); } catch(error){ status.textContent='請使用本機版轉錄'; showToast('線上版不能分析聲音，請下載專案並雙擊開啟SOPStudio.cmd'); } finally { button.disabled=false; } });
function applyTranscriptToSteps(){ if(!transcriptSegments.length)return; steps=transcriptSegments.slice(0,10).map((segment,index)=>{ const text=segment.text.trim(); const title=(text.split(/[。！？，,、]/)[0]||text).slice(0,24); const closest=videoFrames.reduce((best,frame)=>{const distance=Math.abs(parseFloat(frame.timeLabel)-segment.start); return !best||distance<best.distance?{frame,distance}:best;},null); return {title:title||`操作步驟 ${index+1}`,copy:text,note:'請確認這段操作與畫面一致',tag:'語音整理',frameId:closest?.frame.id}; }); selectedIndex=0; renderSteps(); showToast(`已將 ${steps.length} 段語音整理成步驟草稿`); }
$('#applyTranscript').addEventListener('click',()=>{applyTranscriptToSteps(); queueSave();});
$('#topic').addEventListener('input',queueSave);
loadDraft();
renderSteps();
